language: java

sudo: required

services:
  - docker

env:
  global:
    - secure: LcCwZzsQOORS0gWsNNbZiUXMZfTzjJKQuskBLuAKTfYODPSYzj/KUZhhHqXtw/c5r8Ykk2xD1Iiuvi+Ht3JicFSJ/sbPGs0Gj779oxy+kVuIvTuy7IDuBUfTeMlyZhF+/XB4Kp2b2zhvr6yapzpNzloyPX/O2ePm3KAZLvo1kOqqzm8Y7ceCqfPSArOy5eWHItETO0pUemMbOicNKGWgBO3glkr07t+DzXOJa5ZUN3PkXB2Ix7veRYZhHE5MpNjOHMzGY6fgclV3fWq+n+tFyJVmK3xyqcUlbxi67ZsqctSB5Fz7joawPxdVnidJzTKnvv/p+TLdKJ1GwiJ2XwzqUj8u8tgJb71OSq2qTB9iY/pCuLpV7RWBysRtuLiOsrKoUhNNls51su5rFYxvUv9KZe2Yh+NoP7+dgMKuruPvsNKA3w2x3lHb186fiASqgC/m2icpEEcYgNnd5tAGHgGDWxHIY7brzaA6+pcbfD+1wxG8enMuHdJrTFRk0ZOxpRTteTomsm6Xj+6Cf0ktxQcbNkPPssxpKFHO1pMwT57ATe/ia3l3oIADyPNxY4q5S9oCcO6Koj6ckNIdRo9uaVfVkxSeHcH2JKqVHMss/XVdIc50sUtADzJc1Oi9RxGuoSLjZtvr9fU2/Njw1hUnAlEpbT/mNinZlVWALJ3dtEQfCW8=
    - secure: jysGSDczFUHQhdPbrCxQA7ZACOGeGqrCSF+B0CbF1RDBGqiDyTDgcFzNPn1UfY2b7JR50JlVfa2w8jVJBZnt+9RY4PzJk7k9rCsBRrAchK+0/1apyIeV9P75f/JdylsfnLzRqa2ky/Ehgd6tHnTjKuPDd3pA1GFJAhZcdQNJF8tQER6ZOkYNyQmYa2/33Fwfy0Rh0SASqXxliUJgXyZknHB0Bh4FVzjm7IG1ThpFDAO8cmZF4YzG0NYuuHT1T3UXQsSR8QUrH6xEih3Ej0bWviAe/VHI/xsyeRTnIvathlN6eMdZsqkwGFK8w+8jGyqtx9SKDyky3f6F5EzmCSlufTx0gZlolwpy6tflPnta5rq48tMSvLwpSOAHSNnlGWhf6+mMBK0TUthULfp3+cqoFuWfoAVDx4wcmnzqIIJctQBPzl9o0X1zTlfmYd/tDOdHaEW6k9tMrg0X2uStKMWHH90e8ZmnagdmKii9ZJJRmjKYy0l8ZWJsld98tpHbsyDHruCfUDbqI182fn7dT3/K0sA/N+jDhCmwFZQP4Ds/vFFq4AYA28SOe0NvSKaCvWTzvl51oTH8Ej+q3TL9mcXt9Yn4LeHiVe9qBTyoKKVoZVniXfGdJtqPhGthQ4nAHRT5s/ox+DgT2GbJpxt/RYeEZaczLSG6Fi1XDkNOaH7NJ9A=

deploy:
  provider: elasticbeanstalk
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: AWS_SECRET_ACCESS_KEY
  region: "ap-southeast-2"
  app: "condition-report-service-beanstalk"
  env: "condition-report-service-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-362272891583"
  on:
    branch: master

after_deploy:
  - echo "done deploying"