language: minimal
services:
  - docker
sudo: required
before_install:
    - docker build -t condition-report-service .
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: condition-report-api-staging