language: java
sudo: required
services:
  - docker

deploy:
  provider: elasticbeanstalk
  access_key_id:
    - secure: STCCfgdJ6+mxfcCf9BiqClEjOQ0B9nF3yLjzt/cK0wQ/bQO5JhYIapq8KffG/7sk8wZQfHVu4o5JvuI7qxW8hJTPVBeHRXNovCLITDNDGIVH3786GV3OntsOxpSPQmVG364SsuequWQIgzGZrk6qHm34P0wsUUybPnDBp1LopPj4MlxP4lQ4QvDu1WXE5aWc7juzxe2gFn+QTMzFLMwysRTM5Fb39Ox0upWFcbXcpsq6ozEEy2DVei21WQb0pfOUypn6BGEJlHyJDEAj2QAo/tS/e6ioH36F8Co9iUEcUm4yWonwYUev11XW8bn8HXUzrnLVruILtEql0Kvc6rVhlOUfFS0bO3fxQck/p2RRwPGEmaFhiPBzMaXYfhTlFti9foHc+XGy9YrBaXSCirZNYvwe/3GSH6mEiZuZ3qD2enXVQRQfzaRovjQXymhOoB8RU746mGgyeMeRFDSXAertEA3hkGU1b7PC83l5WvY3FQipGL3mG7k9alKig59uWItepXjih5E354yZwpV8i6jdvBCaTQPHCuyaOy68EezqFZE5iG1SAdCgyh4RiXHYCbL+GWz6ModbKb990ybugn6LaH8r1Y4srMJQtrMZDOldu/JMI/CLXYK9gvzr0Pec8xDmQR2kARDngSmc/mrJlJvtbf+COblpFqxdrZgFOtQCgLE=
  secret_access_key:
    - secure: 4LwOjoaFRGtqzU+txrArBgfkdRVhTP7eSWbWrXbXHSZAGDg35PyfDZ7HRtBwlAa0xS3pER8hp9Y4vLV6yi4a1E+KbATlgpycojppL1BVv6uE0ml0q30k0RWLKql5QR21yTfMh4HRg+4cCqqeDu6A5wcewM2k8eeFwsXfmMiwKFcgW4MfNZu5T++D6MgwdITrb2cR6lxN5rAHlit7yMv+MEDRddpAIjMe6VMxPjyjvL1ZTP5OE+rBmGFiYnxybkJwdOzQOsP5XWtfDC613EvCBJuB8sxes/PGYt3CHTVFpYULYFHIZBJb4rK1/dAGlLcuui1o2N09ttsRq0QNdHkjnsoPlOQaiJDoKxFGHgxEsNaIIGSeVWTHzUf24vhr167ruSGnlAwUpv+mQOH9zABjD21vDaryw+WQ/2koPlEOn+hwXR4fIQGJkOQELJRf9DoxEVyEKRrIGYvGwEFyk6BcFZ3AezInSVKt3HYso2JyfU/qXX9cGPXAGu3NhBVnj5KXB6kwqWY8xDZ7itlwwKe8hx4Ld3Iiap8i6+xSLV+/gHafdSX1d8ap8NvHdl/GhnZs/A+e4X0I2L8RsFP1tTy355GP766+7TLmOTm1LXf7XY5fgBNn51hTwJ1ud38/PtbsZLUZQJE4tJQlCDn+8Yp77rvPojT95i7Svm5d1k8qrHo=
  region: ap-southeast-2
  app: condition-report-service-beanstalk
  env: condition-report-service-env
  bucket_name: elasticbeanstalk-ap-southeast-2-362272891583
  on:
    branch: master
    
after_deploy:
  - echo "done deploying"
